server:
  port: 8080

spring:
  profiles:
    include: auth

  datasource:
    driver-class-name: org.h2.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb
        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE
